services:
  - type: web
    name: seonoh-forum
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /ping
